require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
# use_frameworks!
target 'TVapp' do

  # pod 'HPWebKit'
  pod 'SSZipArchive', '~> 2.2'
  platform :ios, '11.0'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'TVappTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'TVapp-tvOS' do

  platform :tvos, '12.0'

  config = use_native_modules!

  # Hermes not yet available on tvOS
  use_react_native!(:path => config["reactNativePath"])

  target 'TVapp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end

post_install do |installer|
  react_native_post_install(installer)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
    
    if (target.name&.eql?('FBReactNativeSpec-iOS'))
      target.build_phases.each do |build_phase|
        if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
          target.build_phases.move(build_phase, 0)
        end
      end
    end
  end
end

